plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  Exclude:
    - 'bin/rails'
    - 'db/*'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'notes/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
FactoryBot/AssociationStyle:
  EnforcedStyle: explicit
Layout/LineLength:
  Max: 120
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/*'
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Max: 70
Metrics/BlockLength:
  Exclude:
    - 'app/admin/*.rb'
    - 'app/api/v1/*.rb'
    - 'app/api/v1/**/*.rb'
    - 'config/**/*'
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30
Metrics/MethodLength:
  Max: 30
RSpec/DescribeClass:
  Exclude:
    - 'spec/acceptance/**/*'
RSpec/ExampleLength:
  Max: 30
RSpec/MultipleExpectations:
  Max: 20
  Exclude:
    - 'spec/acceptance/**/*'
RSpec/MultipleMemoizedHelpers:
  Max: 15
RSpec/NestedGroups:
  Max: 5
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
